### ISSUE TITLE
VPC Link Issue

### ISSUE THREAD

**Issue by ghost** [awsdocs/amazon-vpc-peering-guide#3]
All:

I have reviewed the CoC and Contributing Guidelines, but I apologize if this is left in the wrong format.

1. First, there is an issue in the docs on GovCloud relating to `VPC Links` in `API Gateway`. In differences between API Gateway Commercial and API Gateway GovCloud, it [doesn't mention that this feature is NOT available in GovCloud](https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/govcloud-abp.html).

2. Second, which I am unable to find an answer for online, is why is there no API Gateway Github Repo, or anything related to GovCloud documentation on Github? Are there still service guides "in the pipeline"?

Thank you for reading this, and also for posting these docs on Github in the first place. Look forward to helping where I can in the future.

**Comment by dianeo** [comment]
1. The GovCloud User Guide has now been updated.
2. There are still a few service guides in the pipeline. We are adding them on a best-effort basis. Glad to hear you're finding them helpful!

**Comment by dianeo** [comment]
I'm going to close this issue. But feel free to open a new one (unless you can reopen this one...?) if needed.
