### ISSUE TITLE
Why DNS resolution support is enabled for inter-region VPC peering connection

### ISSUE THREAD

**Issue by jayudhandha** [awsdocs/amazon-vpc-peering-guide#6]
Hi,

I have referred this [docs.](https://docs.aws.amazon.com/vpc/latest/peering/modify-peering-connections.html)

Here you have mentioned below thing.

> You cannot enable DNS resolution support for an inter-region VPC peering connection.

I am not sure that this is correct or not. 

Because i have verified that i am able to resolve DNS in inter-region VPC peering connection.

But as per above docs, This option is disabled from console.

![vpc peering dns resolution](https://user-images.githubusercontent.com/5781316/48064865-1759e200-e1ef-11e8-919a-d2122e30c22b.png)

Please suggest me that either documentation is not currect or functionality mentioned is not implemented correctly.

Thanks!

**Comment by jayudhandha** [comment]
Any help?

**Comment by wolruf** [comment]
AWS recently brought support for this: https://aws.amazon.com/about-aws/whats-new/2018/11/announcing-support-for-dns-resolution-over-inter-region-vpc-peering/
It should work fine for you now.

**Comment by jayudhandha** [comment]
Thanks @wolruf
