### ISSUE TITLE
VPC peering with Edge to Edge Routing Through a VPN Connection or an AWS Direct Connect Connection

### ISSUE THREAD

**Issue by sam0104** [awsdocs/amazon-vpc-peering-guide#7]
referring to https://docs.aws.amazon.com/vpc/latest/peering/invalid-peering-configurations.html , Example: Edge to Edge Routing Through a VPN Connection or an AWS Direct Connect Connection
.
I am building some solution where it  look like below image but I want to access VPC B from corporate network and also from VPC B to go back to corporate network through VPC A. As per the diagram there is VPC peering from VPC A and VPC B (pcx-aaaabbbb) but there is no VPC peering from VPC B to VPC A. 

If I create a two way VPC peering VPC A ----> VPC B and then VPC B to VPC A . 
Then can I access VPC B resources from corporate network  ?
Can I access corporate network resources from VPC B too ?  

Is it possible in any way , please add to document. 

Also here in diagram it is mention corporate network is connecting using Hardware VPN or AWS Direct Connect Connection . If I use some software based VPN solution like AppGate SDP then Can I reach directly from corporate network to VPC B ?

![image](https://user-images.githubusercontent.com/27223479/49916298-53283d00-fe68-11e8-82b9-46f9c8631d81.png)
Thanks 
Sas

**Comment by sam0104** [comment]
For me it is working on one way. I have three VPC

VPC 1 : 20.0.0.0/16 VPC 2 : 10.0.0.0/16 VPC 3 : 172.31.0.0/16 I have VPC peering enable from VPC 1 ----> VPC 3 and VPC 2 ----> VPC 3 . VPC 3 is the acceptor for both VPC peering and VPC 1 and VPC 2 are requestor.

I have one Software based VPN solution running in VPC 3 on public subnet and elastic IP . I have vpn client installed on my laptop.

When I connect to software based VPN ec2 instance running on ( VPC 3 ) , I can access VPC 1 ec2 instances which have only private IP ( in private subnet ) and also I can access VPC 2 ec2 instances with private IP directly from my laptop. No need to login to VPC 3 ec2 and then jump from there to other VPC.

If this scenario is working for me then above diagram from AWS is not correct. Please advise

**Comment by seymours** [comment]
Are you perhaps doing Source NAT on your VPN appliance? If so, that would work as you describe because the traffic is now originating from an IP in VPC3 and be allowed to route via VPC peering to either VPC1 or VPC2

**Comment by sam0104** [comment]
Thanks for your reply. Is it possible using AWS default VPN and direct connect solutions or I need to use same VPN appliance ?

**Comment by seymours** [comment]
Please take a look at the recently announced AWS Transit Gateway - it will enable you build a VPN Connection that then enables you to reach multiple VPC's as you describe. You can find more details here: https://aws.amazon.com/transit-gateway/ - feel free to follow up with any questions in the AWS Forums at https://forums.aws.amazon.com/

**Comment by sam0104** [comment]
Thanks . I think we are somehow using transit-gateway using this VPN appliance.
